version: '2.4'

services:

  postgresql:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=fer45wetp4
      - POSTGRES_DB=project
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - project

  project:
    build: .
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/project
    networks:
        - project
    ports:
      - "8080:8080"

networks:
  project:
    driver: bridge